"""The delivery-first optimiser.

One rule, applied in one place:

    keep only what still pays; among what is left, the fastest wins.

The ordering is lexicographic and the first key is not money:

    1. does the consignment land on the committed date at all
    2. how many days late if not
    3. how soon the freight is moving again
    4. and only as a tie-break, what is left on the bottom line

That fourth key never decides between a fast option and a slow one. It exists
so that two options which land the freight at the same hour do not come back
in an arbitrary order.

WHERE THE OPTIONS COME FROM
---------------------------
Three sources, ranked against each other on the same scale:

    template   the declared playbook actions — switch to rail, part-load,
               escalate to the carrier, notify the customer
    reroute    paths GENERATED by the contingency search with the failed node
               deleted from the graph, which is the half the old playbook
               could not do
    local      a vendor or 3PL near the freight who can take it over today

A generated reroute and a hand-written template compete directly, which is the
point: if the search finds something faster than the template somebody wrote
down years ago, the search should win.

WHAT "RESOLVED" MEANS
---------------------
``hours_to_resolve`` is not the arrival time. It is the hour at which the
consignment is back on a path that will meet its date — the moment the
planner can stop working on it. That is the number a planner is actually
racing, and it is what the dashboard counts down.
"""

from __future__ import annotations

from dataclasses import dataclass
from datetime import timedelta

from engine.clock import Clock
from engine.config import Config
from engine.fast import contingency
from engine.fast import margin as margin_mod
from engine.network.graph import Network
from engine.schemas import ActionOption, GateHit, Mode, Shipment

# Hours to arrange a generated reroute before anything physically moves:
# find capacity, agree a rate, cut the paperwork. Not configurable per path
# because it is a property of the office, not of the route.
REROUTE_SETUP_HOURS = 4.0

# What the planner is told to do when every option has been vetoed or has
# expired. It recovers nothing, and saying so is the honest answer.
LAST_RESORT = "notify_customer"

# An option that leaves this much of the delay behind is managing the
# consequence, not restoring the delivery. Escalating to the carrier (0.80),
# reserving capacity (0.60) and part-loading (0.55) all sit above it; the
# actual re-routings — rail switch 0.15, road reroute 0.20, rail rebook 0.30 —
# all sit below. The line is drawn where the option stops being about getting
# the freight there.
RESTORES_BELOW_RESIDUAL = 0.5


@dataclass(frozen=True)
class FastOption:
    """One way to get this consignment there, priced in time first."""

    option_id: str
    shipment_id: str
    kind: str                     # "template" | "reroute" | "local"
    label: str
    detail: str
    owner: str                    # "us" | "carrier" | "customer" | "vendor"
    hours_to_start: float         # before it can begin
    hours_to_resolve: float       # until the freight is on a viable path
    days_late_after: float
    on_time: bool
    cost_chf: float
    margin: margin_mod.Margin
    route: tuple[str, ...] = ()
    modes: tuple[str, ...] = ()
    contacts: tuple[str, ...] = ()
    expired: bool = False
    expired_reason: str | None = None
    # Does this move the freight, or only manage the consequence of not
    # moving it? Notifying the customer recovers nothing; it converts a missed
    # commitment into an agreed one, which is worth a great deal and is not
    # the same thing. Without this flag the notification wins every ranking on
    # a lane with schedule slack, because it is always the quickest to do.
    restores_delivery: bool = True

    @property
    def executable(self) -> bool:
        """Can the planner set this running without asking anyone outside?

        Only our own levers. A carrier's decision is a request, however fast
        we send it, and presenting a request as a one-click action is the kind
        of dishonesty that loses a planner's trust the first time it does not
        happen.
        """
        return self.owner == "us" and not self.expired

    @property
    def rank_key(self) -> tuple:
        """Lexicographic, and every key before the last one is about time.

        Order: still available, lands on the date, actually moves the freight,
        is ours to execute, how late, how soon it is resolved — and only then
        money, as a tie-break between options that are otherwise identical.

        "Is ours to execute" sits this high because the mandate is speed of
        ACTION. Escalating to the carrier is quick to send and slow to happen:
        it resolves in two hours on paper and leaves the decision with someone
        else. A lever we hold beats a request we make, at equal lateness.
        """
        return (
            self.expired,
            not self.on_time,
            not self.restores_delivery,
            not self.executable,
            round(self.days_late_after, 3),
            round(self.hours_to_resolve, 2),
            -self.margin.margin_chf,
        )

    def as_dict(self) -> dict:
        return {
            "option_id": self.option_id,
            "shipment_id": self.shipment_id,
            "kind": self.kind,
            "label": self.label,
            "detail": self.detail,
            "owner": self.owner,
            "executable": self.executable,
            "hours_to_start": round(self.hours_to_start, 1),
            "hours_to_resolve": round(self.hours_to_resolve, 1),
            "days_late_after": round(self.days_late_after, 2),
            "on_time": self.on_time,
            "cost_chf": round(self.cost_chf, 2),
            "margin_chf": self.margin.margin_chf,
            "margin_headroom_chf": self.margin.headroom_chf,
            "restores_delivery": self.restores_delivery,
            "route": list(self.route),
            "modes": list(self.modes),
            "contacts": list(self.contacts),
            "expired": self.expired,
            "expired_reason": self.expired_reason,
        }


@dataclass(frozen=True)
class Ranking:
    """What survived, what did not, and why — the veto is shown, not hidden."""

    viable: tuple[FastOption, ...]
    vetoed: tuple[tuple[FastOption, str], ...]
    expired: tuple[FastOption, ...]

    @property
    def best(self) -> FastOption | None:
        return self.viable[0] if self.viable else None

    def as_dict(self) -> dict:
        return {
            "best": self.best.as_dict() if self.best else None,
            "options": [o.as_dict() for o in self.viable],
            "vetoed": [
                {**o.as_dict(), "vetoed_because": why} for o, why in self.vetoed
            ],
            "expired": [o.as_dict() for o in self.expired],
        }


# ---------------------------------------------------------------------
def _hours_until(clock: Clock, when) -> float:
    return (when - clock.as_of).total_seconds() / 3600.0


def _days_late(clock: Clock, shipment: Shipment, resolve_hours: float,
               remaining_transit_hours: float) -> float:
    """Days past the committed date if this option is taken now."""
    arrival = clock.as_of + timedelta(hours=resolve_hours + remaining_transit_hours)
    slip = (arrival - shipment.otif_committed_date).total_seconds() / 86400.0
    return max(0.0, round(slip, 3))


def _blocked_nodes(shipment: Shipment, hits: list[GateHit]) -> set[str]:
    return {h.node_id for h in hits if h.shipment_id == shipment.shipment_id}


def _divert_from(shipment: Shipment, hits: list[GateHit], clock: Clock) -> str:
    """Where the freight can actually be turned around.

    The last node it has already cleared, which is not the same as the origin:
    a consignment three legs in cannot be re-planned from the plant. If nothing
    has been cleared yet, the origin is correct.
    """
    blocked = _blocked_nodes(shipment, hits)
    cleared = shipment.origin_node
    for leg in shipment.legs:
        if leg.to_node in blocked:
            break
        if leg.planned_arrive <= clock.as_of:
            cleared = leg.to_node
        else:
            cleared = leg.from_node
            break
    return cleared


def _remaining_planned_hours(shipment: Shipment, clock: Clock) -> float:
    """Planned transit still ahead, used as the do-nothing baseline."""
    return max(0.0, _hours_until(clock, shipment.eta))


def _planned_cost_from(
    shipment: Shipment,
    network: Network,
    config: Config,
    from_node: str,
) -> float:
    """What the PLANNED path still costs from here on.

    This is the baseline a generated reroute is charged against, and it has to
    come from the shipment's own remaining legs rather than from the graph.
    Pricing the plan by re-searching the graph finds the fastest unblocked path
    and calls that the plan — so a road reroute would be compared against a
    road plan and come out free, which is how a barge load gets trucked to
    Rotterdam at no apparent cost.
    """
    cost = 0.0
    counting = from_node == shipment.origin_node
    for leg in shipment.legs:
        if not counting:
            if leg.from_node == from_node:
                counting = True
            else:
                continue
        geometry = network.geometry(leg.from_node, leg.to_node, leg.mode)
        cost += geometry.distance_km * contingency.cost_per_km(config, leg.mode)
        cost += contingency.transfer_chf(config)
    return round(cost, 2)


# ---------------------------------------------------------------------
def from_template(
    action: ActionOption,
    shipment: Shipment,
    config: Config,
    clock: Clock,
    baseline_delay_days: float,
    hours_until_impact: float,
) -> FastOption:
    """Convert a declared playbook action onto the time-first scale."""
    residual_days = baseline_delay_days * action.residual_delay_days
    remaining = _remaining_planned_hours(shipment, clock)

    # A template resolves once it has been executed; the residual delay is
    # then carried by the freight, not by the planner.
    resolve = action.min_hours
    days_late = _days_late(
        clock, shipment, resolve, remaining + residual_days * 24.0
    )

    expired = not action.feasible
    reason = action.infeasible_reason
    if not expired and hours_until_impact < action.min_hours:
        expired = True
        reason = (
            f"needs {action.min_hours:.0f} h and only "
            f"{max(0.0, hours_until_impact):.0f} h remain"
        )

    return FastOption(
        option_id=action.action_id,
        shipment_id=shipment.shipment_id,
        kind="template",
        label=action.label,
        detail=action.description,
        owner=action.owner,
        hours_to_start=action.min_hours,
        hours_to_resolve=resolve,
        days_late_after=days_late,
        on_time=days_late <= 0.0,
        cost_chf=action.cost_chf,
        margin=margin_mod.evaluate(shipment, config, action.cost_chf, days_late),
        contacts=tuple(action.contacts),
        expired=expired,
        expired_reason=reason,
        # The same 0.95 the old playbook used to decide an option "recovers
        # time". Above it, the action leaves the delay essentially intact.
        restores_delivery=action.residual_delay_days < RESTORES_BELOW_RESIDUAL,
    )


def from_path(
    path: contingency.Path,
    shipment: Shipment,
    config: Config,
    network: Network,
    clock: Clock,
    planned_cost_chf: float,
) -> FastOption:
    """Convert a generated path onto the same scale.

    The charge is the DIFFERENCE against the planned path, never the whole
    price of the alternative: the freight was always going to cost something
    to move, and billing the full amount against the disruption would veto
    almost every reroute on a long lane.
    """
    resolve = REROUTE_SETUP_HOURS
    days_late = _days_late(clock, shipment, resolve, path.hours)
    extra = max(0.0, round(path.cost_chf - planned_cost_chf, 2))
    node_names = tuple(network.node(n).name for n in path.node_ids)
    # Name it after what makes it different — the nodes between the ends. Two
    # paths that share a first hop otherwise come back with the same label,
    # and two identically-labelled options is not a choice.
    #
    # Capped at two, because the label is a button and a button that wraps to
    # three lines stops reading as one. The full path is in `detail` and in
    # `route`, so nothing is lost, only moved.
    middle = node_names[1:-1]
    if not middle:
        via = "a direct run"
    elif len(middle) <= 2:
        via = " → ".join(middle)
    else:
        via = f"{middle[0]} → {middle[1]} +{len(middle) - 2} more"

    return FastOption(
        option_id=f"{shipment.shipment_id}:reroute:{'-'.join(path.node_ids)}",
        shipment_id=shipment.shipment_id,
        kind="reroute",
        label=f"Reroute via {via}",
        detail=(
            f"{path.hours:.0f} h moving over {path.distance_km:,.0f} km by "
            f"{'/'.join(sorted({m.value for m in path.modes}))} — "
            f"{' → '.join(node_names)}."
        ),
        owner="us",
        hours_to_start=resolve,
        hours_to_resolve=resolve,
        days_late_after=days_late,
        on_time=days_late <= 0.0,
        cost_chf=extra,
        margin=margin_mod.evaluate(shipment, config, extra, days_late),
        route=tuple(path.node_ids),
        modes=tuple(sorted({m.value for m in path.modes})),
    )


def from_local(
    option: contingency.LocalOption,
    shipment: Shipment,
    config: Config,
    clock: Clock,
    remaining_hours: float,
) -> FastOption:
    """Convert a local vendor handover onto the same scale."""
    resolve = option.handover_hours
    days_late = _days_late(clock, shipment, resolve, remaining_hours)

    return FastOption(
        option_id=f"{shipment.shipment_id}:local:{option.at_node}:{option.vendor}",
        shipment_id=shipment.shipment_id,
        kind="local",
        label=f"Hand over to {option.vendor}",
        detail=(
            f"{option.service.replace('_', ' ')} at {option.at_node_name}, "
            f"{option.distance_km:,.0f} km from the freight. "
            f"Ready in {option.handover_hours:.0f} h."
        ),
        owner="vendor",
        hours_to_start=option.handover_hours,
        hours_to_resolve=resolve,
        days_late_after=days_late,
        on_time=days_late <= 0.0,
        cost_chf=option.cost_chf,
        margin=margin_mod.evaluate(shipment, config, option.cost_chf, days_late),
        contacts=(f"{option.vendor} — {option.phone}",) if option.phone else (),
    )


# ---------------------------------------------------------------------
def rank(options: list[FastOption]) -> Ranking:
    """Veto first, then sort. Never the other way round.

    A loss-making option is not a worse option, it is not an option — so it
    leaves the list before any comparison happens. It is still RETURNED, in
    ``vetoed``, because "we could have trucked it but it would have cost more
    than the load is worth" is a thing a planner needs to be able to say out
    loud, and a silently shortened list cannot say it.
    """
    viable: list[FastOption] = []
    vetoed: list[tuple[FastOption, str]] = []
    expired: list[FastOption] = []

    for option in options:
        if option.expired:
            expired.append(option)
        # The veto is on SPENDING, not on the situation. An option that costs
        # nothing cannot turn a profit into a loss — where the margin is
        # already gone, the delay did that, and vetoing the free option would
        # leave the planner with an empty list at the exact moment they need
        # to be told to ring the customer.
        elif option.cost_chf > 0 and not option.margin.viable:
            vetoed.append((option, option.margin.reason or "below the margin floor"))
        else:
            viable.append(option)

    viable.sort(key=lambda o: o.rank_key)
    vetoed.sort(key=lambda pair: pair[0].rank_key)
    expired.sort(key=lambda o: o.rank_key)

    return Ranking(tuple(viable), tuple(vetoed), tuple(expired))


def for_shipment(
    shipment: Shipment,
    hits: list[GateHit],
    templates: list[ActionOption],
    config: Config,
    network: Network,
    clock: Clock,
    baseline_delay_days: float,
    hours_until_impact: float,
) -> Ranking:
    """Every option for one consignment, on one scale, ranked by speed."""
    options: list[FastOption] = [
        from_template(
            action, shipment, config, clock, baseline_delay_days, hours_until_impact
        )
        for action in templates
    ]

    blocked = _blocked_nodes(shipment, hits)
    origin = _divert_from(shipment, hits, clock)
    destination = shipment.destination_node

    if blocked and origin != destination:
        planned_cost = _planned_cost_from(shipment, network, config, origin)

        for path in contingency.alternatives(
            config, network, origin, destination, blocked
        ):
            options.append(
                from_path(path, shipment, config, network, clock, planned_cost)
            )

        # The fallback only earns its place when the graph has nothing left.
        if not any(o.kind == "reroute" for o in options):
            remaining = _remaining_planned_hours(shipment, clock)
            for local in contingency.local_options(
                config, network, network.point(origin), shipment.value_chf
            )[:3]:
                options.append(
                    from_local(local, shipment, config, clock, remaining)
                )

    return rank(options)


def urgency_band(config: Config, hours: float | None) -> str:
    """One word for how much decision time is left."""
    if hours is None:
        return "unknown"
    bands = (config.raw("fast") or {}).get("urgency_bands", {}) or {}
    if hours <= float(bands.get("now", 2)):
        return "now"
    if hours <= float(bands.get("today", 12)):
        return "today"
    if hours <= float(bands.get("soon", 48)):
        return "soon"
    return "scheduled"


def modes_of(shipment: Shipment) -> tuple[Mode, ...]:
    return tuple(dict.fromkeys(leg.mode for leg in shipment.legs))
