"""Generate the Kaub gauge fixture.

WHY A FIXTURE EXISTS AT ALL
---------------------------
The build environment blocks outbound HTTPS to pegelonline.wsv.de (403 at the
egress proxy), so the live feed cannot be reached from here. Rather than have
the anchor demo depend on a network call, the gauge series is committed.

WHAT THIS FILE IS, PRECISELY
----------------------------
A SHAPED RECONSTRUCTION, not observed data. It reproduces the *profile* of a
Rhine low-water episode — a long summer decline with short rain-driven
recoveries — so the pipeline can be demonstrated and tested end to end. The
centimetre values are generated, not measured.

It is labelled as such inside the JSON, the loader carries that label through,
and the /inputs panel prints it on screen. Nobody should ever be able to mistake
this for a Pegelonline download.

TO REPLACE WITH REAL DATA
-------------------------
Run on a machine with open egress:

    curl "https://www.pegelonline.wsv.de/webservices/rest-api/v2/stations/\\
KAUB/W/measurements.json?start=P30D"

and reshape to {"readings": [{"t": iso8601, "cm": float}, ...]}. For the
multi-year history a hindcast needs, the Pegelonline REST endpoint serves only
a recent window — older Kaub data comes from the WSV/BfG archives instead.
"""

from __future__ import annotations

import json
import math
import random
from datetime import UTC, datetime, timedelta
from pathlib import Path

OUT = Path(__file__).resolve().parent.parent / "data" / "fixtures" / "kaub_levels.json"

AS_OF = datetime(2026, 9, 18, 6, 0, tzinfo=UTC)
DAYS_BACK = 75
READINGS_PER_DAY = 4

# Target profile: a wet spring easing into a dry late summer, ending in the
# band where loading restrictions start to bite and still falling.
START_CM = 225.0
END_CM = 86.0


def build() -> dict:
    rng = random.Random(20260918)
    readings = []
    total_steps = DAYS_BACK * READINGS_PER_DAY

    for step in range(total_steps + 1):
        day_fraction = step / READINGS_PER_DAY
        progress = step / total_steps

        # Recession curves are convex: fast early drop, then a long tail.
        base = END_CM + (START_CM - END_CM) * math.pow(1.0 - progress, 1.15)

        # Two short rain events that interrupt the decline. Without these the
        # series is a clean slope and the trend calculation never gets tested
        # against anything realistic. The later bump is placed so that the
        # series is still in active recession at the as-of instant — a gauge
        # that has been flat for a week is a different decision from one
        # falling four centimetres a day, and the demo needs the second case.
        for peak_day, height, width in ((48.0, 30.0, 5.0), (11.0, 34.0, 5.0)):
            days_ago = DAYS_BACK - day_fraction
            base += height * math.exp(-(((days_ago - peak_day) / width) ** 2))

        # Gauge noise, plus a small daily cycle.
        noise = rng.gauss(0, 1.6) + 1.1 * math.sin(day_fraction * 2 * math.pi)
        level = round(max(20.0, base + noise), 1)

        stamp = AS_OF - timedelta(days=DAYS_BACK) + timedelta(
            hours=step * (24 / READINGS_PER_DAY)
        )
        readings.append({"t": stamp.isoformat().replace("+00:00", "Z"), "cm": level})

    return {
        "station": "KAUB",
        "river": "Rhine",
        "unit": "cm",
        "label": "SHAPED RECONSTRUCTION — not observed data",
        "provenance": "generated by scripts/make_kaub_fixture.py",
        "is_real_data": False,
        "generated_at": datetime.now(UTC).isoformat(),
        "covers": {
            "from": readings[0]["t"],
            "to": readings[-1]["t"],
        },
        "replace_with": (
            "https://www.pegelonline.wsv.de/webservices/rest-api/v2/"
            "stations/KAUB/W/measurements.json?start=P30D"
        ),
        "readings": readings,
    }


if __name__ == "__main__":
    OUT.parent.mkdir(parents=True, exist_ok=True)
    data = build()
    OUT.write_text(json.dumps(data, indent=1))
    last = data["readings"][-1]
    week_ago = data["readings"][-7 * READINGS_PER_DAY]
    slope = (last["cm"] - week_ago["cm"]) / 7.0
    print(f"wrote {OUT} — {len(data['readings'])} readings")
    print(f"latest {last['cm']} cm at {last['t']}, 7-day trend {slope:+.1f} cm/day")
